import { sidebar } from "vuepress-theme-hope";

export default sidebar({
  "/zsxq/": [
    "",
  ],
  "/pmhub/": [
    {
      text: "🔥项目教程",
      collapsible: true,
      children: [
        "about",
        "why",
        "learn",
        "write-to-resume",
        "tech-architecture",
        "product-prototype",
        "api-doc",
        "real-interview",
        "qa",
      ],
    },
    {
      text: "快速开始",
      collapsible: true,
      prefix: "quickstart/",
      children: [
        "environment",
        "backend",
        "frontend",
        "docker",
        "nginx",
      ],
    },
    {
      text: "开篇词",
      collapsible: true,
      prefix: "introduction/",
      children: [
        "beginner-learn",
        "architecture-function",
        "coding-specification",
      ],
    },
    {
      text: "面试系列",
      collapsible: true,
      prefix: "interview/",
      children: [
        "global-filter-statistics-gateway",
        "transmittable-threadlocal-cache-user-data",
        "docker-compose-container-deployment",
        "redis-lock-process-update",
        "monitoring-skywalking",
        "redis-lua-rate-limiting",
        "annotation-aop-auth",
        "sentinel-openfeign",
        "pmhub-seata-consistency",
        "pmhub-rocketmq-push",
        "pmhub-cache-db-consistency",
      ],
    },
    {
      text: "手把手教你搭建启动环境",
      collapsible: true,
      prefix: "environment/",
      children: [
        "putup-mysql",
        "putup-redis",
        "putup-nacos",
        "putup-rocketmq",
        "putup-skywalking",
        "putup-sentinel",
      ],
    },
    {
      text: "产品设计",
      collapsible: true,
      prefix: "productdesign/",
      children: [
        "everyone-is-producter",
        "demand-analysis",
        "project-manage",
        "product-prototype",
      ],
    },
    {
      text: "架构篇",
      collapsible: true,
      prefix: "architecture/",
      children: [
        "scheme-design",
        "tech-select-design",
        "pmhub-gateway",
        "pmhub-nacos",
        "pmhub-openfeign",
        "pmhub-actuator",
        "pmhub-skywalking",
        "pmhub-sentinel",
        "pmhub-aop",
        "pmhub-rocketmq",
        "pmhub-seata",
      ],
    },
    {
      text: "业务篇",
      collapsible: true,
      prefix: "business/",
      children: [
        "overview",
        "user",
        "workflow",
        "dataview",
      ],
    },
    {
      text: "部署篇",
      collapsible: true,
      prefix: "deploy/",
      children: [
        "deploy-window",
        "deploy-macos",
        "deploy-linux",
        "deploy-jenkins",
        "deploy-docker",
        "deploy-ui",
        "deploy-online",
        "deploy-laigeoffer",
      ],
    },
    {
      text: "单体改造微服务避坑指南",
      collapsible: true,
      prefix: "single2microservice/",
      children: [
        "sumup",
        "procedure",
        "bug-mysql",
        "bug-serverconfig",
        "bug-datasource",
        "bug-config-autowired",
        "bug-character-garble",
        "bug-auth",
        "bug-class-loading",
        "bug-mybatis-plus",
      ],
    },
    {
      text: "AI辅助编程实战篇",
      collapsible: true,
      prefix: "aicoding/",
      children: [
        "chatgpt-concept",
        "chatgpt-bug",
        "github-copilot",
        "codeFeex",
      ],
    },
  ],
});
